# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protofiles/quick_ride.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protofiles/quick_ride.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotofiles/quick_ride.proto\"2\n\x0fRegisterRequest\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x0bRideRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\t\"\x1d\n\x0cRideResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"@\n\rDriverRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\t\"\x1f\n\x0e\x44riverResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"/\n\nRideAccept\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\"6\n\x11RideAcceptMessage\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\"\"\n\rStatusRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"!\n\x0cRideComplete\x12\x11\n\tdriver_id\x18\x01 \x01(\t\"\x1e\n\rCompleteReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\x15\n\x13ServerStatusRequest\"F\n\x14ServerStatusResponse\x12\x19\n\x11\x61vailable_drivers\x18\x01 \x01(\x05\x12\x13\n\x0brides_count\x18\x02 \x01(\x05\x32\xf8\x02\n\x10QuickRideService\x12\x35\n\x0eRegisterClient\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12*\n\x0bRequestRide\x12\x0c.RideRequest\x1a\r.RideResponse\x12\x31\n\x0c\x44riverNotify\x12\x0e.DriverRequest\x1a\x0f.DriverResponse0\x01\x12\x33\n\x10SendRideResponse\x12\x0b.RideAccept\x1a\x12.RideAcceptMessage\x12-\n\nRideStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\x12-\n\x0c\x43ompleteRide\x12\r.RideComplete\x1a\x0e.CompleteReply\x12;\n\x0cServerStatus\x12\x14.ServerStatusRequest\x1a\x15.ServerStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofiles.quick_ride_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=31
  _globals['_REGISTERREQUEST']._serialized_end=81
  _globals['_REGISTERRESPONSE']._serialized_start=83
  _globals['_REGISTERRESPONSE']._serialized_end=118
  _globals['_RIDEREQUEST']._serialized_start=120
  _globals['_RIDEREQUEST']._serialized_end=182
  _globals['_RIDERESPONSE']._serialized_start=184
  _globals['_RIDERESPONSE']._serialized_end=213
  _globals['_DRIVERREQUEST']._serialized_start=215
  _globals['_DRIVERREQUEST']._serialized_end=279
  _globals['_DRIVERRESPONSE']._serialized_start=281
  _globals['_DRIVERRESPONSE']._serialized_end=312
  _globals['_RIDEACCEPT']._serialized_start=314
  _globals['_RIDEACCEPT']._serialized_end=361
  _globals['_RIDEACCEPTMESSAGE']._serialized_start=363
  _globals['_RIDEACCEPTMESSAGE']._serialized_end=417
  _globals['_STATUSREQUEST']._serialized_start=419
  _globals['_STATUSREQUEST']._serialized_end=453
  _globals['_STATUSRESPONSE']._serialized_start=455
  _globals['_STATUSRESPONSE']._serialized_end=487
  _globals['_RIDECOMPLETE']._serialized_start=489
  _globals['_RIDECOMPLETE']._serialized_end=522
  _globals['_COMPLETEREPLY']._serialized_start=524
  _globals['_COMPLETEREPLY']._serialized_end=554
  _globals['_SERVERSTATUSREQUEST']._serialized_start=556
  _globals['_SERVERSTATUSREQUEST']._serialized_end=577
  _globals['_SERVERSTATUSRESPONSE']._serialized_start=579
  _globals['_SERVERSTATUSRESPONSE']._serialized_end=649
  _globals['_QUICKRIDESERVICE']._serialized_start=652
  _globals['_QUICKRIDESERVICE']._serialized_end=1028
# @@protoc_insertion_point(module_scope)
